version: '3.4'
networks:
  myAppNetwork:

services:
  Sql:
    container_name: SqlServer
    image: mcr.microsoft.com/mssql/server:latest
    ports:
        - 1433:1433
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=kamol9943
  expensemanagement:
    container_name: expenseappContainer
    image: ${DOCKER_REGISTRY-}expensemanagement
    ports:
        - 8001:80
    build:
      context: .
      dockerfile: src/Web/ExpenseManagement/Dockerfile
    depends_on:
        - Sql


